
annotations: {}
  # service.beta.kubernetes.io/azure-load-balancer-resource-group: corda-k8s # Example annotation for automatic load-balancer

service:
  type: LoadBalancer

ingress:
  enabled: false
  host: corda-node.local

graphdb:
  enabled: true
  host: namespace-graphdb
  port: 7200
  privateRepository: private
  repository: federated

image: corda/community:4.9.2-zulu-openjdk8

notary:
  isNotary: false
  isValidating: false
devMode: true
myLegalName: O=TNO,L=Manila,C=ML,OU=ICT
p2pAddress: 127.0.0.1 # Default value that shouldn't work. Follow instructions in main chart file.
p2pPort: 10005
rpcPort: 10006
adminPort: 10046
rpc:
  address: 0.0.0.0
  adminAddress: 0.0.0.0
security:
  datasourceType: INMEMORY
  users:
    - password: vzzuABeCut3jGoJfEp94
      user: user1
      permissions:
        - ALL
compatibilityZone:
  enabled: true
  compatibilityZoneURL: https://nms.federated-infrastructure.net
secrets:
  create: true
  name: corda-secrets
  networkTrustStore:
    base64: /u3+7QAAAAIAAAADAAAAAgAKbmV0d29ya21hcAAAAZNONlEcAAVYLjUwOQAAAnkwggJ1MIICEqADAgECAghMwgiMj/hB9zAUBggqhkjOPQQDAgYIKoZIzj0DAQcwgYMxCzAJBgNVBAYTAkdCMQ8wDQYDVQQIDAZMb25kb24xDzANBgNVBAcMBkxvbmRvbjEbMBkGA1UECgwSQ29yZGl0ZSBGb3VuZGF0aW9uMSMwIQYDVQQLDBpDb3JkaXRlIEZvdW5kYXRpb24gTmV0d29yazEQMA4GA1UEAwwHUm9vdCBDQTAeFw0yNDExMjAwMDAwMDBaFw0zNDExMTgwMDAwMDBaMFExCzAJBgNVBAYTAkdCMQ8wDQYDVQQHEwZMb25kb24xGzAZBgNVBAoTEkNvcmRpdGUgRm91bmRhdGlvbjEUMBIGA1UEAxMLTmV0d29yayBNYXAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAT7ztCF4T50XFspaGyIU6JN5mVa1dS2DXkNQu/aqtGprhREHxi5vMxyxajoBlMhBo/jlu1UHAFkP/hxmIcB2ri3o4GWMIGTMB0GA1UdDgQWBBRdjh84YSqzKFgDTRCurH71lUwOMTAMBgNVHRMBAf8EAjAAMAsGA1UdDwQEAwIHgDAjBgNVHSUEHDAaBggrBgEFBQcDAQYIKwYBBQUHAwIGBFUdJQAwHwYDVR0jBBgwFoAUIaWSKpq2TkJ11FHUcWa2XV49NwYwEQYKKwYBBAGDimIBAQQDAgECMBQGCCqGSM49BAMCBggqhkjOPQMBBwNHADBEAiBFEXaWESoLeS5yUatrY421XP6hoRB2sw1VfpDYUXeo4AIgCYQo0vIrZ3hTru6E3CnxOwskFQIMzJiAZrAtDafKc/wAAAACABNjb3JkYWludGVybWVkaWF0ZWNhAAABk042URwABVguNTA5AAACsDCCAqwwggJIoAMCAQICCAgiflG1RnXBMBQGCCqGSM49BAMCBggqhkjOPQMBBzCBgzELMAkGA1UEBhMCR0IxDzANBgNVBAgMBkxvbmRvbjEPMA0GA1UEBwwGTG9uZG9uMRswGQYDVQQKDBJDb3JkaXRlIEZvdW5kYXRpb24xIzAhBgNVBAsMGkNvcmRpdGUgRm91bmRhdGlvbiBOZXR3b3JrMRAwDgYDVQQDDAdSb290IENBMB4XDTI0MTEyMDAwMDAwMFoXDTM0MTExODAwMDAwMFowgYMxCzAJBgNVBAYTAkdCMQ8wDQYDVQQIDAZMb25kb24xDzANBgNVBAcMBkxvbmRvbjEbMBkGA1UECgwSQ29yZGl0ZSBGb3VuZGF0aW9uMSMwIQYDVQQLDBpDb3JkaXRlIEZvdW5kYXRpb24gTmV0d29yazEQMA4GA1UEAwwHRG9vcm1hbjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABOk5THvTPI0q8X00OzQ0ZfMMd8bhB/Pxt4aD4h0WUmmr3PJvL+Upb6CrXYMDsewLVYuP0cAhHbw/U6cvuG4VxbmjgZkwgZYwHQYDVR0OBBYEFJNzc4p7SEIH5HH6YuEpbPkNsVtXMA8GA1UdEwEB/wQFMAMBAf8wCwYDVR0PBAQDAgGGMCMGA1UdJQQcMBoGCCsGAQUFBwMBBggrBgEFBQcDAgYEVR0lADAfBgNVHSMEGDAWgBQhpZIqmrZOQnXUUdRxZrZdXj03BjARBgorBgEEAYOKYgEBBAMCAQEwFAYIKoZIzj0EAwIGCCqGSM49AwEHA0gAMEUCIE0yrHbhYC11If1AbJFA6b96Oc8o+9JbhHd6fAOy8js0AiEA03IB1lZ1PGj27G7/YlYjh7i54cwJ+hWxt9iwileL1roAAAACAAtjb3JkYXJvb3RjYQAAAZNONlEcAAVYLjUwOQAAAp0wggKZMIICNaADAgECAggxQabZKNZAwTAUBggqhkjOPQQDAgYIKoZIzj0DAQcwgYMxCzAJBgNVBAYTAkdCMQ8wDQYDVQQIDAZMb25kb24xDzANBgNVBAcMBkxvbmRvbjEbMBkGA1UECgwSQ29yZGl0ZSBGb3VuZGF0aW9uMSMwIQYDVQQLDBpDb3JkaXRlIEZvdW5kYXRpb24gTmV0d29yazEQMA4GA1UEAwwHUm9vdCBDQTAeFw0yNDExMjAwMDAwMDBaFw0zNDExMTgwMDAwMDBaMIGDMQswCQYDVQQGEwJHQjEPMA0GA1UECAwGTG9uZG9uMQ8wDQYDVQQHDAZMb25kb24xGzAZBgNVBAoMEkNvcmRpdGUgRm91bmRhdGlvbjEjMCEGA1UECwwaQ29yZGl0ZSBGb3VuZGF0aW9uIE5ldHdvcmsxEDAOBgNVBAMMB1Jvb3QgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASs10gMvnpYUyycxZzy8FrLWpMYes6Tb/0o4rNWDwSEJwsoB56GwAWjlhJCvwfkotLy0Y6K0a0+ms3HiylejIIso4GGMIGDMB0GA1UdDgQWBBQhpZIqmrZOQnXUUdRxZrZdXj03BjAPBgNVHRMBAf8EBTADAQH/MAsGA1UdDwQEAwIBhjAjBgNVHSUEHDAaBggrBgEFBQcDAQYIKwYBBQUHAwIGBFUdJQAwHwYDVR0jBBgwFoAUIaWSKpq2TkJ11FHUcWa2XV49NwYwFAYIKoZIzj0EAwIGCCqGSM49AwEHA0gAMEUCIQDa7vBr4hyxvSwX6YCF05QkXWHaypg9VE+hX0lYAsRbgQIgKGGGoSP8CbRdDj1RNJpUbpabQXkMDRCrDbhOvR7HJvw0d8Mrw2x2d8ngmr36hDqnTpdy/g==

dataFetcherType: sparql
dataFetcherGetEndpointUrl: http://some.api.example
dataFetcherRmlEndpointUrl: https://some.rml.url
